# Generated by Django 5.2.7 on 2025-10-12 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_product_rating_product_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.product'),
        ),
    ]
