# Generated by Django 5.2.7 on 2025-10-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_product_rating_remove_product_review_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='blog/'),
        ),
    ]
