# Generated by Django 5.2.7 on 2025-10-12 04:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_blogpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Test/'),
            preserve_default=False,
        ),
    ]
