# Generated by Django 5.2.7 on 2025-10-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='logo',
            new_name='image',
        ),
    ]
