# Generated by Django 5.2.7 on 2025-10-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_cart_cartitem_order_orderitem_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/')),
            ],
        ),
    ]
