# Generated by Django 5.2.7 on 2025-10-19 20:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='carousel',
            name='button_text',
            field=models.CharField(default='Shop Now', max_length=50),
        ),
        migrations.AddField(
            model_name='carousel',
            name='button_url',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='carousel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carousel',
            name='subtitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
